### ISSUE TITLE
Redo

### ISSUE THREAD

**Issue by tenplus1** [acmgit/cucina_vegana#1]
Farming Redo can also use the farming.register_plant() function from default farming mod and grow crops using redo features :) the *_redo.lua files aren't required.

Also... great mod :)

**Comment by acmgit** [comment]
Special thanks for the hint, i've tested it and changed it, so there no more *_default.lua and *_redo.lua files. Now all is found in the file of the plant itself.

Thx, in near future i will add more recipes, which use more of your addon ;-).

**Comment by tenplus1** [comment]
Thanks for letting me know, the register_plant() function has been fixed and is working a-ok again :)

**Comment by acmgit** [comment]
Ok, now it seems to work, i'm testing again ;-).
