### ISSUE TITLE
Crafting cucina_vegana:rice_flour replaces too much

### ISSUE THREAD

**Issue by Bastrabun** [acmgit/cucina_vegana#10]
Crafting cucina_vegana:rice_flour replaces 3 stone and 3 cobble with 9 stone and 9 cobble.

```
minetest.register_craft({
	output = "cucina_vegana:rice_flour",
	recipe = {	{"default:stone", "default:stone", "default:stone"},
				{"cucina_vegana:rice", "cucina_vegana:rice", "cucina_vegana:rice"},
                {"default:cobble", "default:cobble", "default:cobble"}
			},
    replacements = {
                {"default:stone", "default:stone 3"},
                {"default:cobble", "default:cobble 3"}
            }

})
```

Happens in all combinations, but only when your crafting grid will not be empty afterwards. So place at least 2 of each ingredient. 

Same problem reversed, if you do it like this:

`{"default:stone", "default:stone 3"},` =>  `{"default:stone", "default:stone"},`

In this case, you only get the replacements back, if there is not more than one of each ingredient present.

Is suspected crafting issues in unified inventory, but works the same way in default inv.

Might that be an engine bug?

**Comment by acmgit** [comment]
Yes, i think it's a bug in the engine. This way worked fine for me, so i implemented it. If you get 9 items back, then there is this bug fixed and the recipes has to change without the numbers in the replacements.
