### ISSUE TITLE
Feature request: export bonemeal_list unconditionally

### ISSUE THREAD

**Issue by mazes-80** [acmgit/cucina_vegana#11]
Hi, I'm reworking [maidroid](https://gitlab.com/mazes_80/maidroid) mod.

It now supports cucina_vegana, but to be able to harvest plants, I use the cucina_vegana.plant_settings.bonemeal_list.
If this table was initialized the  by all the plants, I wouldn't have to require bonemeal in my mod.

I mean in all plants change
`if(cucina_vegana.plant_settings.bonemeal) then`
`    table.insert(cucina_vegana.plant_settings.bonemeal_list,`
`                 {"cucina_vegana:" .. pname .. "_", step, "cucina_vegana:" .. pname .. "_seed"})`

`end -- if(cucina_vegana.plant_settings.bonemeal`
to
`table.insert(cucina_vegana.plant_settings.bonemeal_list,
    {"cucina_vegana:" .. pname .. "_", step, "cucina_vegana:" .. pname .. "_seed"})`

**Comment by acmgit** [comment]
I'm glad to hear, that other mods supports cucina_vegana :-).
Have you changed it in your version? Perhaps you can send me a PR.

Next is, there are 2 versions of plants, one with the vanilla farming and one with the farming_plus mod. The difference is in pname .. "_seed".

Greetings, Clyde

**Comment by mazes-80** [comment]
I didn't change the mod as I use bonemeal everywhere (especially when testing), but I still can send a PR.

About the two plants version, I use [farming_redo](https://notabug.org/TenPlus1/Farming) and it matches the test
`farming and farming.mod and farming.mod = "redo"`
so germ_launch is set to "_seed", but this mod requires it to be 1
so I set this in minetest.conf
`cucina_vegana.plant_settings.germ_launch = 1`

would be nice to have extra checking to automatize compatibility, and I just figure out it is also a problem for the mod i'm reworking.
feedback would be nice if you find some way to solve this.

**Comment by acmgit** [comment]
Yes, a PR would be fine.

The Problem between farming and farming_redo is, that farming_redo isn't so compatible to farming, it works fine instead farming, but changes this.
This was also the reason, why i included this setting.
The automatic checking happens between farming and farming_redo.
Since now, i have only this solution to hold the mod compatible between both farmings.

**Comment by acmgit** [comment]
Special Thanks for the PR, i added it to the code.
Greetings, Clyde.
