### ISSUE TITLE
seed_plantname <-> plantname_seed aliases

### ISSUE THREAD

**Issue by mazes-80** [acmgit/cucina_vegana#19]
To take care of the bug you opened for maidroid. I needed to switch between farming and farming_redo some times.

I could see a lot of unknown nodes:
with default farming nodes are named: "cucina_vegana:seed_" .. plantname
with farming redo they are named:       "cucina_vegana:" .. plantname .. "_seed"

I think you might register aliases

**Comment by acmgit** [comment]
Thx for the PR, i've merged it.
