### ISSUE TITLE
Various minor bugs/typos

### ISSUE THREAD

**Issue by axcore** [acmgit/cucina_vegana#22]
- The texture `cucina_vegana_onion_7.png` only exists as 32x32, there is no 16x16 version
- The texture `cucina_vegana_rice_starch.png` only exists as 32x32, there is no 16x16 version
- In the 16x16 texture folder, files are named `cucina_vegan_garlic_1.png` etc, instead of `cucina_vegana_garlic_1.png`
- In the 16x16 texture folder, all the `flax` files are misspelled as `flex` files
- In the 16x16 texture folder, `cucina_vegana_banana_item.png` should not include the `item` part
- Comments in various files (e.g. `chili-redo.lua`) mention `chives` instead of `chilis`, etc
- Some wild plants have `not_in_creative_inventory`, most of them don't, for no obvious reason
- `cucina_vegana:sea_salad` has no crafting recipe, unless the aqua_farming mod is installed 
- Blueberry puree should be spelled with only one R (the item's description is misspelled)
- In the 16x16 texture folder, the texture for blueberry puree is also misspelled, it should have only one R
- In `recipes_5xx.lua`, `replacements` is misspelled as `repclaements`
- The craft recipe for `cucina_vegana:imitation_butter` uses 2 x `cucina_vegana:soy_milk`, but only returns 1 x  `vessels:drinking_glass`. Two glasses should probably be returned

**Comment by acmgit** [comment]
Thanks for your big list, i've fixed all.
