### ISSUE TITLE
Improve hunger mod compatibility (currently crashes with Voxelgarden and does not support hbhunger)

### ISSUE THREAD

**Issue by j-r** [acmgit/cucina_vegana#29]
cucina_vegana is calling ``hunger.register_food`` when it detects a mod called ``hunger``. It's not clear which ``hunger`` mod this code was based on and a short search on the ContentDB didn't turn up any candidates. Can you point me in the right direction?

(Voxelgarden's builtin hunger mod that doesn't currently have that function and I'm curious what it is supposed to do in order to possibly add a compatibility function to increase VG's compatibility with MTG mods.)

**Comment by acmgit** [comment]
Cucina Vegana supports two hunger-mods.
One old mod called hunger, was often installed with the mods food and diet.
One newer mod by Dirk, hunger_ng.

**Comment by j-r** [comment]
Thanks for the pointers! I think I found it: https://github.com/BlockMen/hunger

I guess there is a mod name conflict with https://forum.minetest.net/viewtopic.php?t=3114 which probably is the base for Voxelgarden's [hunger](https://content.minetest.net/modnames/hunger/) which seems to be the only mod named ``hunger`` on the content DB, but several mods on the content DB optionally depend on hunger and at a cursory glance they want the one from Blockmen.

I'll open an issue with Voxelgarden to resolve this ambiguity.

But even if this gets fixed in the future, I think it might make sense for cucina_vegana to:

- check that hunger.register_food actually exists before calling it to prevent crashing with old/current versions of Voxelgarden

- maybe add support for [hbhunger](https://content.minetest.net/modnames/hbhunger/) which seems to be API compatible to Blockmen's mod and is provided by several games on the contentdb

- or alternatively check whether it is even necessary to register with hunger and hbhunger at all; because cucina_vegana has no poison items it might not be needed, at least nobody seems to have missed hbhunger support so far:-)

I'll edited the title of the issue accordingly.

**Comment by j-r** [comment]
Voxelgarden git has renamed it's hunger mod to ``vg_hunger``.

**Comment by acmgit** [comment]
Hmm, should i add vg_hunger to the mods?

**Comment by acmgit** [comment]
I've added the hunger-support for Voxelgarden. Hoping the code is correct for this. Look at the file register_mods.

**Comment by j-r** [comment]
Sorry, I wasn't clear. Voxelgarden has no ``hunger.register_food()``, so the new section is not a good idea. Please revert it.

I just tested a bit and it is not necessary to do anything for hunger support in CV. Just using ``minetest.item_eat()`` as is already done seems to be enough.

On the VG side the MTG farming compatibility has to be improved to actually make the plants grow. I'll open a PR for VG to fix that over there.

There is one other thing I haven't fully investigated yet. If necessary I'll open a separate Issue/PR.

**Comment by j-r** [comment]
Ok, the other issue is not related to Voxelgarden. I opened a PR with a trivial fix.

**Comment by acmgit** [comment]
Well, i revert the changes for the Hunger-Support.

**Comment by j-r** [comment]
Thank you! I did the VG PR here: https://codeberg.org/voxelgarden/voxelgarden/pulls/132

**Comment by acmgit** [comment]
Great ;-)
