### ISSUE TITLE
Crafting sunflower returns unknown item

### ISSUE THREAD

**Issue by Bastrabun** [acmgit/cucina_vegana#7]
Looks like the recipe cannot properly decide on the replacement. I correctly get the seeds, but also get an unknown item called `group:dye,color_yellow`

```
minetest.register_craft({
	type = "shapeless",
	output = "cucina_vegana:sunflower_seeds 4",
	recipe = {"flowers:sunflower"},
	replacements = {
		{"flowers:sunflower", "group:dye,color_yellow"}
	}
})
```

Maybe replace in recipes.lua line 571 

{"flowers:sunflower", "group:dye,color_yellow"}

with 

{"flowers:sunflower", "dye:yellow"}

**Comment by acmgit** [comment]
Thanks for the hint, it seems the api in MT has changed, i has fixed the code.
