### ISSUE TITLE
Seeds don't sprout

### ISSUE THREAD

**Issue by Bastrabun** [acmgit/cucina_vegana#8]
I have the latest version of cucina_vegana and also the latest version of farming_redo. Server is on 5.3.0

I tried it in singleplayer with only MTG, farmind_redo and cucina_vegana

The farming_redo seeds grow into crops, the cucina_vegana ones don't

I have tilled earth (farming:soil) beside a waterblock (default:water_source)

For my reference: #111

**Comment by acmgit** [comment]
Yes, i know this behaviour, this was the reason, why cucina_vegana is divided in a normal part and a farming_redo part.
In farming_redo, it should start as sproutling and not at seed, so the plant will grow.
I've added a setting: cucina_vegana.plant_settings.germ_launch.
Defalult is 0, set it to 1 and it should work. But you will not see the seed on the soil.
Greetings, Clyde.

**Comment by Bastrabun** [comment]
Thanks, it works with this setting!

Suggest update documentation and then close :)

Let the harvest begin

**Comment by acmgit** [comment]
Glad that i could help you.
Of course, you're right, i have to update the documentation ;-).
Greetings, Clyde.
