### ISSUE TITLE
Some recipes return an unknown item

### ISSUE THREAD

**Issue by Bastrabun** [acmgit/cucina_vegana#9]
It may be related to a group item in their replacements, like cucina_vegana:salad_bowl

Or this one:

```
minetest.register_craft({
	output = "cucina_vegana:salad_hollandaise",
	recipe = {	{"cucina_vegana:parsley", "cucina_vegana:lettuce", "cucina_vegana:chives"},
				{"cucina_vegana:sauce_hollandaise", "group:food_oil", ""},
				{"", "group:food_bowl", ""}
			},
    replacements = {
                {"group:food_oil", "vessels:glas_bottle"},
				{"cucina_vegana:sauce_hollandaise", "vessels:glass_bottle"}
			}

})
```

For my reference 446

**Comment by acmgit** [comment]
Hello Bastrabun,

thank you for reporting me the bug.
This was a typo in the recipes file. At the lines 586, 597 and 618 there stands in the replacemants glas_bottle, but there are **glass_bottle** ;-).

This is now fixed, please update your version.

Greetings, Clyde.
